#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set wallpaper
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $SCRIPTPATH/background.png
fi

# Launch picom/compton if installed
if [ -x "$(command -v picom)" ]; then
  pkill picom
  picom &
fi

if [ -x "$(command -v compton)" ]; then
  pkill compton
  compton &
fi

# Launch polybar if installed
if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  polybar -c "$SCRIPTPATH/polybar.config" &
fi
