#!/usr/bin/env bash

# PipeWire
start-pipewire-x11 &

# Cursor
xsetroot -cursor_name left_ptr

export SCRIPTPATH="$(
  cd "$(dirname "$0")" || exit
  pwd -P
)"

if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Launch dunst
if [ -x "$(command -v dunst)" ]; then
  dunst &
fi

# Restore nitrgoen
if [ -x "$(command -v nitrogen)" ]; then
  nitrogen --restore &
fi

# Launch picom if installed
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends &
fi

# Launch polybar if installed
if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  polybar -c "$SCRIPTPATH/polybar.config" &
fi
